import '../styles/globals.css'
import { Roboto_Flex as RobotoFlex } from 'next/font/google'

import Sidebar from '@/components/sidebar'

const roboto = RobotoFlex({ subsets: ['latin'] })

export const metadata = {
  title: 'PEAL',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-pt">
      <body className={`${roboto.className} flex`}>
        <Sidebar />
        <div className="flex-1 p-7">{children}</div>
      </body>
    </html>
  )
}
